### ISSUE TITLE
是否可以增加关键词屏蔽功能？

### ISSUE THREAD

**Issue by ychgithub** [Virtual-Dimension/TrulyShield#1]
你好，是否可以增加关键词屏蔽功能？有时候知乎的时间线会推送很多“娱乐”新闻。
刷知乎的初衷是为了开阔眼界，了解一些知识，尽管浅薄，但胜在内容丰富，现在时间线上充斥着大量两性问题、感性问题、个人问题还有娱乐新闻，希望可以增加关键词屏蔽功能，如果问题标题中有关键词，即可屏蔽整个问题，使得时间线更加简洁。

**Comment by Xciyang** [comment]
主要不好解决关键词词库的问题，还有用户人性化词库的设置和存储上实现起来较为复杂。

**Comment by ychgithub** [comment]
请问能否让用户自己把关键词，录入到代码中？以字典的形式，让用户自行编辑。
这样词库的设置、存储问题就解决了。
目前脚本可以将设置好的话题关键词自动屏蔽，非常好用。但如果能针对标题就更好了。
太感谢了。目前也够用了。

**Comment by Xciyang** [comment]
> 请问能否让用户自己把关键词，录入到代码中？以字典的形式，让用户自行编辑。
> 这样词库的设置、存储问题就解决了。
> 目前脚本可以将设置好的话题关键词自动屏蔽，非常好用。但如果能针对标题就更好了。
> 太感谢了。目前也够用了。

现在已经实现让用户自己设置屏蔽关键字，并且是针对标题进行屏蔽的。

似乎知乎的算法比较智能，不会给用户推送包含不感兴趣话题关键词（在知乎的用户设置中）的问题和回答。

@ychgithub
